routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "Front\FrontController@index")->name("index");

Route::get("post/{slug}", "Front\FrontController@single_post")->name("post");

Route::get("category/{slug}", "Front\FrontController@category_post")->name("category_post");

Route::get("tag/{slug}", "Front\FrontController@tag_post")->name("tag_post");





Route::group(["middleware" => ["auth"]], function(){

	Route::get("/dashboard" , 		"Admin\AdminController@admin")->name("dashboard");
	Route::resource("tags", 		"Admin\TagController");
	Route::resource("categories", 	"Admin\CategoryController");
	Route::resource("posts", 		"Admin\PostController");

	// //Categories Routes
	// Route::resource("dashboard/tags", 		"Admin\TagController");
	// Route::get("categories", "Admin\CategoryController")->name("categories");
	// Route::resource("dashboard/posts", 		"Admin\PostController");

	// Route::match(["get","post"], "dashboard-admin-ecommerce/create-category-product", "Dashboard\Product\CategoryController@createCategory")->name("create-category-product");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/footer.blade.php
<div class="row-fluid">
  <div id="footer" class="span12"> 2019 &copy; Visio. Diseñado por <a href="https://solid-script.com.ve">Solid Script</a> </div>
</div>
<!--end-Footer-part-->
<script src="{{ asset('admin/js/excanvas.min.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.min.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.ui.custom.js') }}"></script> 
<script src="{{ asset('admin/js/bootstrap.min.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.flot.min.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.flot.resize.min.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.peity.min.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.js') }}"></script> 
<script src="{{ asset('admin/js/fullcalendar.min.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.calendar.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.chat.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.validate.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.form_validation.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.wizard.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.uniform.js') }}"></script> 
<script src="{{ asset('admin/js/select2.min.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.popover.js') }}"></script> 
<script src="{{ asset('admin/js/jquery.dataTables.min.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.tables.js') }}"></script> 
<script src="{{ asset('admin/js/matrix.interface.js') }}"></script> 
<script type="text/javascript">
  // This function is called from the pop-up menus to transfer to
  // a different page. Ignore if the value returned is a null string:
  function goPage (newURL) {

      // if url is empty, skip the menu dividers and reset the menu selection to default
      if (newURL != "") {
      
          // if url is "-", it is this page -- reset the menu:
          if (newURL == "-" ) {
              resetMenu();            
          } 
          // else, send page to designated URL            
          else {  
            document.location.href = newURL;
          }
      }
  }

// resets the menu selection upon entry to this page:
function resetMenu() {
   document.gomenu.selector.selectedIndex = 2;
}
</script>

resources/views/layouts/admin/header.blade.php
<!--Header-part-->
<div id="header">
  <h1><a href="dashboard.html">Panel de Administración</a></h1>
</div>
<!--close-Header-part--> 

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Bienvenido {{ Auth::user()->name }}</span><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="{{ route("index") }}" target="_blank"><i class="icon-eye-open"></i> Ver Blog</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
        <li class="divider"></li>
        <li><a href="login.html"><i class="icon-key"></i> Log Out</a></li>
      </ul>
    </li>
    <li class="dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
        <li class="divider"></li>
        <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
        <li class="divider"></li>
        <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
        <li class="divider"></li>
        <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
      </ul>
    </li>
    <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
    <li class=""><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
  </ul>
</div>

<!--start-top-serch-->
<div id="search">
  <input type="text" placeholder="Search here..."/>
  <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
</div>
<!--close-top-serch--> 

resources/views/layouts/admin/messages.blade.php
		@if(session("info"))
	        <div class="alert alert-success alert-block"> <a class="close" data-dismiss="alert" href="#">×</a>
	              <h4 class="alert-heading">¡Hecho!</h4>
	              {{ session("info") }}. 
	        </div>
        @endif

        @if(count($errors))
        	 <div class="alert alert-danger alert-block"> <a class="close" data-dismiss="alert" href="#">×</a>
	              <h4 class="alert-heading">¡Error!</h4>
	               <ul>
		               	@foreach($errors->all() as $error)
		               		<li>{{ $error }}</li>
		                @endforeach
	               </ul>
	        </div>
        @endif

resources/views/layouts/admin/sidebar.blade.php
<div id="sidebar">
  <a href="{{ route("dashboard") }}" class="visible-phone">
    <i class="icon icon-home"></i> Dashboard
  </a>
  <ul>
    <li class="{{ Request::is('dashboard') ? 'active' : '' }}">
      <a href="{{ route("dashboard") }}">
        <i class="icon icon-home"></i> <span>Dashboard</span>
      </a> 
    </li>

    <li class="submenu {{ Request::is('posts') ? 'active' : '' }}"> 
      <a href="#"><i class="icon icon-th-list"></i> 
        <span>Posts</span>
      </a>
      <ul>
        <li class="{{ Request::is('posts') ? 'active' : '' }}">
          <a href="{{ route("posts.index")}}">Ver Posts</a>
        </li>
        <li class="{{ Request::is('posts.create') ? 'active' : '' }}">
          <a href="{{ route("posts.create")}}">Crear Post</a>
        </li>
      </ul>
    </li>

   <li class="submenu {{ Request::is('categories') ? 'active' : '' }}">
      <a href="#"><i class="icon icon-sitemap"></i> 
        <span>Categorías</span>
      </a>
      <ul>
        <li class="{{ Request::is('categories') ? 'active' : '' }}">
          <a href="{{ route("categories.index")}}">
            <i class="fas fa-bullseye"></i> Ver categorías
          </a>
      </li>
        <li class="{{ Request::is('categories.create') ? 'active' : '' }}">
          <a href="{{ route("categories.create") }}">Crear Categoría</a>
        </li>
      </ul>
    </li>

    <li class="submenu {{ Request::is('tags') ? 'active' : '' }}"> 
      <a href="#"><i class="icon icon-th-list"></i> 
        <span>Etiquetas</span>
      </a>
      <ul>
        <li class="{{ Request::is('tags') ? 'active' : '' }}">
          <a href="{{ route("tags.index")}}">Ver Etiquetas</a>
        </li>
        <li class="{{ Request::is('tags.create') ? 'active' : '' }}">
          <a href="{{ route("tags.create")}}">Crear Etiqueta</a>
        </li>
      </ul>
    </li>
    
    
    
  
    <li class="content"> <span>Monthly Bandwidth Transfer</span>
      <div class="progress progress-mini progress-danger active progress-striped">
        <div style="width: 77%;" class="bar"></div>
      </div>
      <span class="percent">77%</span>
      <div class="stat">21419.94 / 14000 MB</div>
    </li>
    <li class="content"> <span>Disk Space Usage</span>
      <div class="progress progress-mini active progress-striped">
        <div style="width: 87%;" class="bar"></div>
      </div>
      <span class="percent">87%</span>
      <div class="stat">604.44 / 4000 MB</div>
    </li>
  </ul>
</div>

resources/views/layouts/admin/theme_admin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Panel de Administración Vision</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ asset('admin/css/bootstrap.min.css')}} " />
    <link rel="stylesheet" href="{{ asset('admin/css/bootstrap-responsive.min.css')}} " />
    <link rel="stylesheet" href="{{ asset('admin/css/fullcalendar.css')}} " />
    <link rel="stylesheet" href="{{ asset('admin/css/matrix-style.css')}} " />
    <link rel="stylesheet" href="{{ asset('admin/css/matrix-media.css')}} " />
    <link href="{{ asset('admin/font-awesome/css/font-awesome.css')}} " rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
    @yield("styles")
  </head>
  <body>

    @include("layouts.admin.header")

    <!--sidebar-menu-->
    @include("layouts.admin.sidebar")

    <!--content-->
    <div id="content">
      @yield("content")
    </div>

    <!--Footer-part-->
    @include("layouts.admin.footer")
    @yield("scripts")
  </body>
</html>